var fs = require('fs');

var html = fs.readFileSync('index.html','utf8');

// convert to something that should work in a .h file
var escaped = html.replace(/\\/g,'\\\\').replace(/\"/g,'\\"').replace(/[\n\t]/g,'').replace(/(\r\n|\n|\r)/gm,"");

var hFile = `// NOTE: don't edit manually, this is generated by build-hbml.js

const char* HTMLPAGE="${escaped}";`

fs.writeFileSync('include/HTMLPAGE.h',hFile);
